### ISSUE TITLE
Filter the default app (module) name for core module names

### ISSUE THREAD

**Issue by philBrown** [henyojess/generator-gulp-ng#10]
Ok, so this appears to be a bit of an edge case but still a tricky one to debug...

I had named my app directory "ng" (I'm evaluating several frameworks and naming the directories after each) and after running `yo gulp-ng`, my app was created with modules _ng_ and _ng-main_.

Having my module overwrite the core _ng_ module broke several dependencies across the app (_ngRoute_ in particular) so this might be something to look out for.

**Comment by henyojess** [comment]
@philBrown how do you propose we prevent this? we could detect the name of the project and stop if it is named ng?
