### ISSUE TITLE
Jade support

### ISSUE THREAD

**Issue by m-shulipa** [henyojess/generator-gulp-ng#2]
As I understand, your generator was developed without supporting Jade syntax?
Is t possible to add it to generator?
For example: yo gulp-ng --jade

**Comment by henyojess** [comment]
@nshulipa gulp-ng is for frontend only

**Comment by m-shulipa** [comment]
@henyojess Jade is the frontend tool
Check http://jade-lang.com/

**Comment by niallobrien** [comment]
Yes, but you want to use Jade & Angular together? Seems a little strange to me.

**Comment by lobo-tuerto** [comment]
It is not strange, it's common to write your angular views or partial in jade, in fact it is common to write your HTML in Jade for web apps. Angular is for making webapps.
