### ISSUE TITLE
how to create controllers, services and directives ?

### ISSUE THREAD

**Issue by mlmarius** [henyojess/generator-gulp-ng#7]
can you please show how to create the custom stuff ? The files say "controller code goes here" or "service goes here" but i don't know how i should write it so that the build works. Thanks.

**Comment by e-oz** [comment]
Looks abandoned.

**Comment by henyojess** [comment]
@jamm not really abandoned, things are just a bit hectic

**Comment by henyojess** [comment]
@mlmarius, sorry for the late reply, check out the main controller generated
